/**
 * \file
 *
 * \brief User board configuration template
 *
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

// Configure/Deconfigure hardware on the module
#define TRAQPAQ_HW_PWM_ENABLED			TRUE
#define TRAQPAQ_HW_EBI_ENABLED			TRUE
#define TRAQPAQ_HW_USART_ENABLED		TRUE
#define TRAQPAQ_HW_SPI_ENABLED			TRUE
#define TRAQPAQ_HW_SPI_DMA_ENABLED		FALSE
#define TRAQPAQ_HW_TWI_ENABLED			TRUE
#define TRAQPAQ_HW_EXINT_ENABLED		FALSE
#define TRAQPAQ_HW_USB_ENABLED			TRUE
#define TRAQPAQ_HW_DEBUG_ENABLED		FALSE	// FreeRTOS Trace
#define TRAQPAQ_HW_PLL_ENABLED			TRUE
#define TRAQPAQ_HW_WDT_ENABLED			TRUE

#define TRAQPAQ_HW_USB_FASTCHG_ENABLED	TRUE

#define TRAQPAQ_PDCA_SPI_ENABLED		FALSE
#define TRAQPAQ_PCDA_USART0_ENABLED		FALSE
#define TRAQPAQ_PCDA_USART1_ENABLED		FALSE
#define TRAQPAQ_PCDA_TWI_ENABLED		FALSE

#endif // CONF_BOARD_H
